name: gaia_space
description: A comprehensive DevOps collaboration platform
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6
  # Network and API
  dio: ^5.3.2
  graphql_flutter: ^5.1.2
  # Database
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3
  # Auth
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  # UI
  flutter_markdown: ^0.6.18
  fl_chart: ^0.64.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  http: ^1.1.0
  drag_and_drop_lists: ^0.4.2
  flutter_colorpicker: ^1.0.3
  date_time_picker: ^2.1.0
  url_launcher: ^6.1.12
  # Git integration
  git: ^2.2.1
  # Utilities
  intl: ^0.17.0
  logger: ^1.4.0
  equatable: ^2.0.5
  uuid: ^3.0.7
  file_picker: ^5.5.0
  flutter_fancy_tree_view: ^1.1.0
  flutter_slidable: ^3.0.1
  diff_match_patch: ^0.4.1
  code_text_field: ^1.1.0
  # Testing
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  drift_dev: ^2.11.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # Uncomment when font files are available
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300