import { createResource, createSignal, For, Show } from "solid-js";
import { personalApi, type Absence } from "../api/personal";
import "./Absences.css";
import { ProfilePicker } from "../components/Pickers";
import { humanError, profileId as sessionProfile } from "../session";

const blank=()=>({profile_id:sessionProfile(),reason_type:"",date_from:"",date_to:"",approved:false});
export default function Absences() {
  const [profileId,setProfileId]=createSignal(""); const [form,setForm]=createSignal(blank()); const [error,setError]=createSignal("");
  const [absences,{refetch}]=createResource(profileId,id=>personalApi.absences(id||undefined));
  const save=async(e:SubmitEvent)=>{e.preventDefault();try{const f=form();if(!f.profile_id.trim()||!f.reason_type.trim()||!f.date_from||!f.date_to)throw new Error("Profile, reason, and dates are required.");await personalApi.createAbsence({...f,profile_id:f.profile_id.trim(),reason_type:f.reason_type.trim()});setForm(blank());refetch()}catch(reason){setError(humanError(reason))}};
  const update=async(absence:Absence,patch:Partial<Absence>)=>{try{await personalApi.updateAbsence({...absence,...patch});refetch()}catch(reason){setError(humanError(reason))}};
  return <section class="absence-view"><header><div><h1>Absences</h1><p>Planned, current, and historical availability across your organization.</p></div><ProfilePicker label="Filter profile" value={profileId()} onChange={setProfileId} allowAll/></header><Show when={error()}><p class="absence-error">{error()}</p></Show><div class="absence-layout"><form class="absence-card" onSubmit={save}><h2>Record absence</h2><ProfilePicker label="Profile" value={form().profile_id||sessionProfile()} onChange={id=>setForm({...form(),profile_id:id})}/><input placeholder="Reason or type" value={form().reason_type} onInput={e=>setForm({...form(),reason_type:e.currentTarget.value})}/><label>From<input type="date" value={form().date_from} onInput={e=>setForm({...form(),date_from:e.currentTarget.value})}/></label><label>To<input type="date" value={form().date_to} onInput={e=>setForm({...form(),date_to:e.currentTarget.value})}/></label><label class="absence-approved"><input type="checkbox" checked={form().approved} onChange={e=>setForm({...form(),approved:e.currentTarget.checked})}/> Approved</label><button class="primary">Save absence</button></form><div class="absence-list"><For each={absences()}>{absence=><article class="absence-row"><div><strong>{absence.reason_type}</strong><span>{absence.profile_id}</span><time>{absence.date_from} — {absence.date_to}</time></div><label><input type="checkbox" checked={absence.approved} onChange={e=>update(absence,{approved:e.currentTarget.checked})}/> Approved</label><button class="ghost" title="Delete absence" onClick={async()=>{try{await personalApi.deleteAbsence(absence.id);refetch()}catch(reason){setError(humanError(reason))}}}>×</button></article>}</For></div></div></section>;
}
