import { createEffect, createMemo, createSignal, For, Show, onCleanup, onMount } from "solid-js";
import PageHeader, { Chip } from "../components/PageHeader";
import { Icon } from "../components/Icon";
import { route } from "../router";
import { CRM_STAGES, PIPELINE_STAGES, emptyLocation, id, loadCrm, saveCrm, type Account, type ActivityKind, type Contact, type CrmStage, type Location } from "../crmStore";
import "./CRM.css";

const split = (value: string) => value.split(/[,\n]/).map(x => x.trim()).filter(Boolean);
const date = (value: string) => value ? new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(`${value}T12:00:00`)) : "Kein Termin";
type CrmView = "Pipeline" | "Kunden" | "Offene Deals" | "Abgeschlossene Deals" | "Kalender";
const viewForRouteTab = (tab: string | undefined): CrmView => ({ pipeline: "Pipeline", customers: "Kunden", open: "Offene Deals", closed: "Abgeschlossene Deals", calendar: "Kalender" }[tab ?? "pipeline"] ?? "Pipeline");
const dealStage = (item: { account: Account; location: Location }) => item.account.dealScope === "Betrieb" ? item.account.stage : item.location.stage;
const dealStatus = (item: { account: Account; location: Location }) => item.account.dealScope === "Betrieb" ? item.account.status : item.location.status;
function DropZone(props: { label: string; tone: "lost" | "won"; onDrop: (locationId: string) => void }) { return <div data-crm-terminal={props.tone} class={`crm-drop-zone ${props.tone}`} onDragEnter={e => e.preventDefault()} onDragOver={e => { e.preventDefault(); if (e.dataTransfer) e.dataTransfer.dropEffect = "move"; }} onDrop={e => { e.preventDefault(); const locationId = e.dataTransfer?.getData("text/plain"); if (locationId) props.onDrop(locationId); }}>{props.label}</div> }

export default function CRM() {
  const [accounts, setAccounts] = createSignal<Account[]>(loadCrm());
  const [selected, setSelected] = createSignal<string | null>(null);
  const [query, setQuery] = createSignal("");
  const [cityFilter, setCityFilter] = createSignal("");
  const [postalFilter, setPostalFilter] = createSignal("");
  const [newOpen, setNewOpen] = createSignal(false);
  const [filterOwner, setFilterOwner] = createSignal("Alle");
  const [view, setView] = createSignal<CrmView>(viewForRouteTab(route().tab));
  createEffect(() => setView(viewForRouteTab(route().tab)));
  const [dragging, setDragging] = createSignal<string | null>(null);
  const [pointerDrag, setPointerDrag] = createSignal<{ id: string; x: number; y: number } | null>(null);
  const [dragOverStage, setDragOverStage] = createSignal<CrmStage | null>(null);
  let pointerCandidate: { id: string; x: number; y: number } | null = null;
  let suppressCardClick = false;
  createEffect(() => saveCrm(accounts()));
  const locations = createMemo(() => accounts().flatMap(account => account.locations.map(location => ({ account, location }))));
  /** One business is one deal by default; a business can deliberately opt into separate site deals. */
  const visible = () => accounts().flatMap(account => (account.dealScope === "Standorte" ? account.locations : [account.locations[0]]).filter(Boolean).map(location => ({ account, location }))).filter(({ account }) => {
    const q = query().trim().toLocaleLowerCase("de");
    const addresses = account.locations.map(location => location.address).join(" ").toLocaleLowerCase("de");
    return (!q || `${account.name} ${addresses}`.toLocaleLowerCase("de").includes(q)) && (!cityFilter().trim() || addresses.includes(cityFilter().trim().toLocaleLowerCase("de"))) && (!postalFilter().trim() || addresses.includes(postalFilter().trim())) && (filterOwner() === "Alle" || account.owner === filterOwner());
  });
  const selectedItem = () => locations().find(item => item.location.id === selected());
  const mutate = (fn: (draft: Account[]) => void) => setAccounts(current => { const next = structuredClone(current); fn(next); return next; });
  const updateLocation = (locationId: string, patch: Partial<Location>) => mutate(items => { for (const account of items) { const loc = account.locations.find(x => x.id === locationId); if (loc) Object.assign(loc, patch); } });
  const move = (locationId: string, stage: CrmStage) => mutate(items => { const account = items.find(item => item.locations.some(location => location.id === locationId)); if (!account) return; account.stage = stage; account.status = "Aktiv"; if (account.dealScope === "Betrieb") account.locations.forEach(location => { location.stage = stage; location.status = "Aktiv"; }); else { const location = account.locations.find(item => item.id === locationId); if (location) { location.stage = stage; location.status = "Aktiv"; } } });
  const addAccount = (name: string, owner: string) => { const location = emptyLocation(name); const account: Account = { id: id("account"), name, website: "", locationCount: 1, employees: "", decisionMaker: "", software: "", source: "", owner, stage: "Non-Qualified", status: "Aktiv", dealScope: "Betrieb", locations: [location] }; mutate(items => items.unshift(account)); setSelected(location.id); setNewOpen(false); };
  const owners = () => ["Alle", ...Array.from(new Set(accounts().map(x => x.owner).filter(Boolean)))];
  const cityOptions = () => Array.from(new Set(accounts().flatMap(account => account.locations.map(location => location.address.match(/\b\d{5}\s+([^\n]+)/)?.[1]?.trim()).filter((city): city is string => !!city)))).sort((a, b) => a.localeCompare(b, "de"));
  const postalOptions = () => Array.from(new Set(accounts().flatMap(account => account.locations.map(location => location.address.match(/\b(\d{5})\b/)?.[1]).filter((postal): postal is string => !!postal)))).sort();
  onMount(() => {
    const moved = (event: PointerEvent) => {
      const candidate = pointerCandidate;
      if (!candidate) return;
      if (!pointerDrag() && Math.hypot(event.clientX - candidate.x, event.clientY - candidate.y) < 6) return;
      const target = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-crm-stage]");
      setPointerDrag({ id: candidate.id, x: event.clientX, y: event.clientY });
      setDragOverStage((target?.dataset.crmStage as CrmStage | undefined) ?? null);
    };
    const released = (event: PointerEvent) => {
      const active = pointerDrag();
      if (active) {
        const target = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-crm-stage], [data-crm-terminal]");
        const stage = target?.dataset.crmStage as CrmStage | undefined;
        const terminal = target?.dataset.crmTerminal;
        if (stage) move(active.id, stage);
        if (terminal === "won") move(active.id, "Gewonnen");
        if (terminal === "lost") mutate(items => { const account = items.find(item => item.locations.some(location => location.id === active.id)); if (account) { account.status = "Verloren"; account.locations.forEach(location => location.status = "Verloren"); } });
        suppressCardClick = true;
      }
      pointerCandidate = null; setPointerDrag(null); setDragOverStage(null);
    };
    window.addEventListener("pointermove", moved); window.addEventListener("pointerup", released);
    onCleanup(() => { window.removeEventListener("pointermove", moved); window.removeEventListener("pointerup", released); });
  });
  return <section class="crm-view">
    <PageHeader icon="columns" title="CRM" subline="Betriebe und Standorte im Vertrieb verwalten." chips={<Chip value={visible().length} label={visible().length === 1 ? " Standort" : " Standorte"} />} />
    <nav class="page-actionbar crm-toolbar" aria-label="CRM actions">
      <div class="crm-search"><Icon name="search" size={17}/><input value={query()} onInput={e => setQuery(e.currentTarget.value)} placeholder="Betrieb oder Standort suchen" aria-label="Betrieb oder Standort suchen" /></div>
      <select class="crm-filter-input" aria-label="Nach Stadt filtern" value={cityFilter()} onChange={e => setCityFilter(e.currentTarget.value)}><option value="">Alle Städte</option><For each={cityOptions()}>{city => <option value={city}>{city}</option>}</For></select>
      <select class="crm-filter-input" aria-label="Nach Postleitzahl filtern" value={postalFilter()} onChange={e => setPostalFilter(e.currentTarget.value)}><option value="">Alle PLZ</option><For each={postalOptions()}>{postal => <option value={postal}>{postal}</option>}</For></select>
      <select aria-label="Nach verantwortlicher Person filtern" value={filterOwner()} onChange={e => setFilterOwner(e.currentTarget.value)}><For each={owners()}>{owner => <option>{owner}</option>}</For></select>
      <button class="primary" onClick={() => setNewOpen(true)}><Icon name="plus" size={16}/> Betrieb hinzufügen</button>
    </nav>
    <Show when={newOpen()}><NewAccount onClose={() => setNewOpen(false)} onSave={addAccount}/></Show>
    <Show when={pointerDrag()}>{drag => <div class="crm-drag-ghost" style={{ left: `${drag().x + 14}px`, top: `${drag().y + 14}px` }}>Standort verschieben</div>}</Show>
    <Show when={view() === "Pipeline"}><section class="crm-pipeline"><div class="crm-pipeline-summary"><span>{visible().filter(x => dealStatus(x) === "Aktiv" && dealStage(x) !== "Gewonnen").length} offene Deals</span><span>Pipeline: Vertrieb</span></div><div class="crm-board" aria-label="Vertriebspipeline">
      <For each={PIPELINE_STAGES}>{stage => <section class="crm-column" data-crm-stage={stage} classList={{ "is-drop-target": dragOverStage() === stage }} onDragEnter={e => { e.preventDefault(); setDragOverStage(stage); }} onDragOver={e => { e.preventDefault(); if (e.dataTransfer) e.dataTransfer.dropEffect = "move"; setDragOverStage(stage); }} onDragLeave={() => setDragOverStage(null)} onDrop={e => { e.preventDefault(); const locationId = e.dataTransfer?.getData("text/plain") || dragging(); if (locationId) move(locationId, stage); setDragging(null); setDragOverStage(null); }}>
        <header><strong>{stage}</strong><span>{visible().filter(x => dealStage(x) === stage && dealStatus(x) === "Aktiv").length}</span></header>
        <div class="crm-column-cards"><For each={visible().filter(x => dealStage(x) === stage && dealStatus(x) === "Aktiv")}>{item => <div class="crm-card" role="button" tabindex="0" onPointerDown={e => { pointerCandidate = { id: item.location.id, x: e.clientX, y: e.clientY }; }} onClick={() => { if (suppressCardClick) { suppressCardClick = false; return; } setSelected(item.location.id); }}>
          <span class="crm-card-account">{item.account.locations.length} Standort{item.account.locations.length === 1 ? "" : "e"}</span><strong>{item.account.dealScope === "Betrieb" ? item.account.name : item.location.name}</strong>
          <Show when={item.location.nextStep}><span class="crm-card-next"><Icon name="alert" size={14}/>{item.location.nextStep}</span></Show>
          <footer><span>{item.account.owner || "Nicht zugeteilt"}</span><Show when={item.location.contacts.length}><span>{item.location.contacts.length} Kontakt{item.location.contacts.length === 1 ? "" : "e"}</span></Show></footer>
        </div>}</For></div>
      </section>}</For>
    </div><Show when={pointerDrag()}><div class="crm-terminal-zones"><span>Deal abschließen</span><DropZone label="Verloren" tone="lost" onDrop={locationId => updateLocation(locationId, { status: "Verloren" })}/><DropZone label="Gewonnen" tone="won" onDrop={locationId => move(locationId, "Gewonnen")}/></div></Show></section></Show>
    <Show when={view() === "Kunden"}><CustomerDirectory title="Kundenkarteien" items={visible} onOpen={setSelected}/></Show>
    <Show when={view() === "Offene Deals"}><CustomerDirectory title="Offene Deals" items={() => visible().filter(x => dealStatus(x) === "Aktiv" && dealStage(x) !== "Gewonnen")} onOpen={setSelected}/></Show>
    <Show when={view() === "Abgeschlossene Deals"}><CustomerDirectory title="Abgeschlossene Deals" items={() => visible().filter(x => dealStatus(x) === "Verloren" || dealStage(x) === "Gewonnen")} onOpen={setSelected}/></Show>
    <Show when={view() === "Kalender"}><CrmCalendar items={visible} onOpen={setSelected}/></Show>
    <Show when={selectedItem()}>{item => <Detail locationId={item().location.id} accounts={accounts} onSelect={setSelected} onClose={() => setSelected(null)} onMutate={mutate} onUpdate={updateLocation} onMove={move}/>}</Show>
  </section>;
}

function NewAccount(props: { onClose: () => void; onSave: (name: string, owner: string) => void }) {
  const [name, setName] = createSignal(""); const [owner, setOwner] = createSignal("Jannes");
  return <div class="crm-overlay" role="presentation"><form class="crm-modal" onSubmit={e => { e.preventDefault(); if (name().trim()) props.onSave(name().trim(), owner()); }}><header><h2>Neuen Betrieb anlegen</h2><button type="button" class="icon-button" onClick={props.onClose}><Icon name="close"/></button></header><label>Betriebsname<input autofocus value={name()} onInput={e => setName(e.currentTarget.value)} placeholder="z. B. Optik Musterstadt"/></label><label>Verantwortliche Person<select value={owner()} onChange={e => setOwner(e.currentTarget.value)}><For each={["Jannes", "Bjarne", "Charles", "Pascal"]}>{x => <option>{x}</option>}</For></select></label><p>Der erste Standort wird angelegt und kann anschließend in der Kundenkartei ergänzt werden.</p><footer><button type="button" class="ghost" onClick={props.onClose}>Abbrechen</button><button class="primary">Betrieb anlegen</button></footer></form></div>;
}

function Detail(props: { locationId: string; accounts: () => Account[]; onSelect: (id: string) => void; onClose: () => void; onMutate: (fn: (draft: Account[]) => void) => void; onUpdate: (id: string, patch: Partial<Location>) => void; onMove: (id: string, stage: CrmStage) => void }) {
  const [tab, setTab] = createSignal<"Übersicht" | "Aktivitäten" | "Dokumente">("Übersicht");
  let detailEl: HTMLElement | undefined;
  createEffect(() => { props.locationId; requestAnimationFrame(() => detailEl?.scrollTo({ top: 0 })); });
  const location = () => props.accounts().flatMap(x => x.locations).find(x => x.id === props.locationId)!;
  const account = () => props.accounts().find(x => x.locations.some(location => location.id === props.locationId))!;
  const patchAccount = (patch: Partial<Account>) => props.onMutate(items => { const found = items.find(x => x.id === account().id); if (found) Object.assign(found, patch); });
  const addContact = () => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); loc?.contacts.push({ id: id("contact"), name: "", role: "", emails: [], phones: [], preferred: "" }); });
  const addNote = (title: string, body: string) => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); if (loc && body.trim()) loc.notes.unshift({ id: id("note"), title: title.trim() || "Notiz", body: body.trim(), author: "Team paloptic", createdAt: new Date().toISOString() }); });
  const addActivity = (kind: ActivityKind, title: string, dueDate: string, outcome: string) => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); if (loc && title.trim()) { loc.activities.unshift({ id: id("activity"), kind, title, dueDate, outcome: outcome.trim(), done: false }); if (outcome.trim()) loc.notes.unshift({ id: id("note"), title: `${kind}: ${title}`, body: outcome.trim(), author: "Team paloptic", createdAt: new Date().toISOString() }); } });
  const addLocation = () => { const next = { ...emptyLocation(`${account().name} · Neuer Standort`), stage: account().stage, status: account().status }; props.onMutate(items => { const found = items.find(x => x.id === account().id); if (found) { found.locations.push(next); found.locationCount = found.locations.length; } }); props.onSelect(next.id); };
  return <aside ref={detailEl} class="crm-detail" aria-label={`Kundenkartei ${location().name}`}>
    <header class="crm-detail-head"><div><button class="crm-back" onClick={props.onClose}><Icon name="chevron-left" size={17}/> Pipeline</button><p>{account().name}</p><h1>{location().name}</h1></div><button class="icon-button" onClick={props.onClose} aria-label="Kundenkartei schließen"><Icon name="close"/></button></header>
    <div class="crm-stage-row"><select value={location().stage} onChange={e => props.onMove(location().id, e.currentTarget.value as CrmStage)}><For each={CRM_STAGES}>{stage => <option>{stage}</option>}</For></select><button class="ghost danger" onClick={() => props.onMutate(items => { const found = items.find(item => item.id === account().id); if (found) { found.status = "Verloren"; found.locations.forEach(location => location.status = "Verloren"); } })}>Als verloren markieren</button></div>
    <nav class="crm-tabs"><For each={["Übersicht", "Aktivitäten", "Dokumente"] as const}>{name => <button classList={{ active: tab() === name }} onClick={() => setTab(name)}>{name}</button>}</For></nav>
    <Show when={tab() === "Übersicht"}><div class="crm-detail-body"><section class="crm-section"><h2>Betrieb</h2><div class="crm-fields two"><Field label="Betriebsname" value={account().name} onChange={value => patchAccount({ name: value })}/><Field label="Website" value={account().website} onChange={value => patchAccount({ website: value })}/><label>Anzahl Standorte<input value={String(account().locations.length)} readOnly/></label><Field label="Entscheider (betriebsübergreifend)" value={account().decisionMaker ?? ""} onChange={value => patchAccount({ decisionMaker: value })}/><Field label="Mitarbeitende gesamt" value={account().employees} onChange={value => patchAccount({ employees: value })}/><Field label="Branchensoftware" value={account().software} onChange={value => patchAccount({ software: value })}/><Field label="Quelle" value={account().source} onChange={value => patchAccount({ source: value })}/><Field label="Verantwortliche Person" value={account().owner} onChange={value => patchAccount({ owner: value })}/><label>Deal-Führung<select value={account().dealScope} onChange={e => patchAccount({ dealScope: e.currentTarget.value as Account["dealScope"] })}><option value="Betrieb">Ein Deal für den gesamten Betrieb</option><option value="Standorte">Separate Deals je Standort</option></select></label></div></section>
      <section class="crm-section"><div class="crm-section-title"><h2>Standorte</h2></div><div class="crm-location-list"><For each={account().locations}>{loc => <button classList={{ active: loc.id === location().id }} onClick={() => props.onSelect(loc.id)}>{loc.name}<small>{loc.stage}</small></button>}</For><button class="crm-add-location-card" onClick={addLocation}><Icon name="plus" size={15}/><span>Neuen Standort hinzufügen</span><small>Eigene Kontaktdaten und Ansprechpartner</small></button></div><h3>Stammdaten und Kontaktdaten dieses Standorts</h3><Field label="Standortname" value={location().name} onChange={value => props.onUpdate(location().id, { name: value })}/><Field label="Mitarbeitende an diesem Standort" value={location().employees ?? ""} onChange={value => props.onUpdate(location().id, { employees: value })}/><label>Adresse<textarea value={location().address} onInput={e => props.onUpdate(location().id, { address: e.currentTarget.value })} placeholder="Straße, Hausnummer&#10;PLZ Ort"/></label><Field label="E-Mail-Adressen" value={location().emails.join(", ")} onChange={value => props.onUpdate(location().id, { emails: split(value) })}/><Field label="Telefonnummern" value={location().phones.join(", ")} onChange={value => props.onUpdate(location().id, { phones: split(value) })}/></section>
      <section class="crm-section"><div class="crm-section-title"><h2>Ansprechpartner</h2><button class="ghost small" onClick={addContact}><Icon name="plus" size={14}/> Kontakt</button></div><For each={location().contacts}>{contact => <ContactForm contact={contact} onPatch={patch => props.onMutate(items => { const found = items.flatMap(x => x.locations).find(x => x.id === location().id)?.contacts.find(x => x.id === contact.id); if (found) Object.assign(found, patch); })}/>}</For><Show when={!location().contacts.length}><p class="crm-empty">Noch keine Ansprechpartner hinterlegt.</p></Show></section>
      <section class="crm-section"><h2>Nächster Schritt</h2><Field label="Aufgabe / nächster Kontakt" value={location().nextStep} onChange={value => props.onUpdate(location().id, { nextStep: value })}/><label>Fällig am<input type="date" value={location().nextStepDate} onInput={e => props.onUpdate(location().id, { nextStepDate: e.currentTarget.value })}/></label></section>
      <Notes notes={location().notes} onAdd={addNote}/></div></Show>
    <Show when={tab() === "Aktivitäten"}><Activities activities={location().activities} onAdd={addActivity} onToggle={activityId => props.onMutate(items => { const a = items.flatMap(x => x.locations).find(x => x.id === location().id)?.activities.find(x => x.id === activityId); if (a) a.done = !a.done; })}/></Show>
    <Show when={tab() === "Dokumente"}><Files location={location} onAdd={file => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); loc?.files.unshift(file); })}/></Show>
  </aside>;
}
const Field = (props: { label: string; value: string; onChange: (value: string) => void }) => <label>{props.label}<input value={props.value} onInput={e => props.onChange(e.currentTarget.value)}/></label>;
function CustomerDirectory(props: { title: string; items: () => { account: Account; location: Location }[]; onOpen: (id: string) => void }) { return <section class="crm-directory"><header><div><h2>{props.title}</h2><p>Betrieb auswählen, um die vollständige Kundenkartei mit allen Standorten zu öffnen.</p></div><span>{props.items().length}</span></header><div class="crm-directory-table"><div class="crm-directory-head"><span>Betrieb</span><span>Standorte</span><span>Pipeline</span><span>Nächster Schritt</span><span>Verantwortlich</span></div><For each={props.items()}>{item => <button onClick={() => props.onOpen(item.location.id)}><strong>{item.account.dealScope === "Betrieb" ? item.account.name : item.location.name}</strong><span>{item.account.dealScope === "Betrieb" ? `${item.account.locations.length} Standorte` : item.account.name}</span><span class="crm-stage-chip">{dealStatus(item) === "Verloren" ? "Verloren" : dealStage(item)}</span><span>{item.location.nextStep || "—"}</span><span>{item.account.owner || "—"}</span></button>}</For></div><Show when={!props.items().length}><p class="crm-empty">Keine Einträge in dieser Ansicht.</p></Show></section> }
function CrmCalendar(props: { items: () => { account: Account; location: Location }[]; onOpen: (id: string) => void }) { const activities = () => props.items().flatMap(item => item.location.activities.filter(a => !a.done).map(activity => ({ ...item, activity }))).sort((a,b) => a.activity.dueDate.localeCompare(b.activity.dueDate)); return <section class="crm-directory crm-calendar"><header><div><h2>CRM-Kalender</h2><p>Offene Aktivitäten und nächste Schritte nach Datum.</p></div><span>{activities().length}</span></header><For each={activities()}>{entry => <button class="crm-calendar-row" onClick={() => props.onOpen(entry.location.id)}><time>{date(entry.activity.dueDate)}</time><span><strong>{entry.activity.kind} · {entry.activity.title}</strong><small>{entry.location.name} · {entry.account.name}</small></span><Icon name="chevron-right" size={17}/></button>}</For><Show when={!activities().length}><p class="crm-empty">Noch keine offenen Aktivitäten geplant.</p></Show></section> }
function ContactForm(props: { contact: Contact; onPatch: (patch: Partial<Contact>) => void }) { return <div class="crm-contact"><div class="crm-fields two"><Field label="Name" value={props.contact.name} onChange={name => props.onPatch({ name })}/><Field label="Rolle" value={props.contact.role} onChange={role => props.onPatch({ role })}/><Field label="E-Mail-Adressen" value={props.contact.emails.join(", ")} onChange={value => props.onPatch({ emails: split(value) })}/><Field label="Telefonnummern" value={props.contact.phones.join(", ")} onChange={value => props.onPatch({ phones: split(value) })}/></div><Field label="Bevorzugter Kontaktweg" value={props.contact.preferred} onChange={preferred => props.onPatch({ preferred })}/></div>; }
function Notes(props: { notes: Location["notes"]; onAdd: (title: string, body: string) => void }) { const [open, setOpen] = createSignal(false); const [title, setTitle] = createSignal(""); const [body, setBody] = createSignal(""); return <section class="crm-section"><div class="crm-section-title"><h2>Notizen</h2><button class="ghost small" onClick={() => setOpen(true)}><Icon name="plus" size={14}/> Notiz</button></div><Show when={open()}><form class="crm-add-note" onSubmit={e => { e.preventDefault(); props.onAdd(title(), body()); setTitle(""); setBody(""); setOpen(false); }}><input value={title()} onInput={e => setTitle(e.currentTarget.value)} placeholder="Titel, z. B. Gespräch vom 14.09."/><textarea value={body()} onInput={e => setBody(e.currentTarget.value)} placeholder="Gesprächsnotiz festhalten…"/><div><button type="button" class="ghost" onClick={() => setOpen(false)}>Abbrechen</button><button class="primary">Notiz speichern</button></div></form></Show><div class="crm-notes-list"><For each={props.notes}>{note => <details class="crm-note"><summary><strong>{note.title ?? "Notiz"}</strong><small>{new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(note.createdAt))}</small></summary><p>{note.body}</p><small>{note.author}</small></details>}</For></div><Show when={!props.notes.length}><button class="crm-add-note-card" onClick={() => setOpen(true)}><Icon name="plus" size={17}/><span>Erste Notiz hinzufügen</span><small>Gespräch, Entscheidung oder wichtige Information dokumentieren</small></button></Show></section>; }
function Activities(props: { activities: Location["activities"]; onAdd: (kind: ActivityKind, title: string, due: string, outcome: string) => void; onToggle: (id: string) => void }) { const [kind, setKind] = createSignal<ActivityKind>("Anruf"); const [title, setTitle] = createSignal(""); const [due, setDue] = createSignal(""); const [outcome, setOutcome] = createSignal(""); return <div class="crm-detail-body"><section class="crm-section"><h2>Aktivität planen oder dokumentieren</h2><form class="crm-activity-form" onSubmit={e => { e.preventDefault(); props.onAdd(kind(), title(), due(), outcome()); setTitle(""); setDue(""); setOutcome(""); }}><select value={kind()} onChange={e => setKind(e.currentTarget.value as ActivityKind)}><For each={["Anruf", "E-Mail", "Besuch", "Video-Call", "Aufgabe"] as ActivityKind[]}>{x => <option>{x}</option>}</For></select><input value={title()} onInput={e => setTitle(e.currentTarget.value)} placeholder="Was ist zu tun?"/><input type="date" value={due()} onInput={e => setDue(e.currentTarget.value)}/><textarea value={outcome()} onInput={e => setOutcome(e.currentTarget.value)} placeholder="Gesprächsergebnis oder Entscheidung – wird als Notiz gespeichert"/><button class="primary">Hinzufügen</button></form></section><section class="crm-section"><h2>Verlauf</h2><For each={props.activities}>{activity => <label class="crm-activity"><input type="checkbox" checked={activity.done} onChange={() => props.onToggle(activity.id)}/><span><strong>{activity.kind} · {activity.title}</strong><small>{date(activity.dueDate)}</small></span></label>}</For><Show when={!props.activities.length}><p class="crm-empty">Noch keine Aktivitäten geplant.</p></Show></section></div>; }
function Files(props: { location: () => Location; onAdd: (file: Location["files"][number]) => void }) { const upload = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => props.onAdd({ id: id("file"), name: file.name, type: file.type, data: String(reader.result), createdAt: new Date().toISOString() }); reader.readAsDataURL(file); }; return <div class="crm-detail-body"><section class="crm-section"><h2>Dokumente</h2><label class="crm-upload"><Icon name="upload" size={20}/><span>Datei hinzufügen</span><input type="file" onChange={e => upload(e.currentTarget.files?.[0])}/></label><p class="crm-muted">Angebote, Verträge und weitere Unterlagen werden direkt an diesem Standort hinterlegt.</p><For each={props.location().files}>{file => <a class="crm-file" href={file.data} download={file.name}><Icon name="doc" size={18}/><span><strong>{file.name}</strong><small>{date(file.createdAt.slice(0, 10))}</small></span></a>}</For><Show when={!props.location().files.length}><p class="crm-empty">Noch keine Dokumente hinterlegt.</p></Show></section></div>; }
