import { createEffect, createMemo, createSignal, For, Show } from "solid-js";
import PageHeader, { Chip } from "../components/PageHeader";
import { Icon } from "../components/Icon";
import { CRM_STAGES, emptyLocation, id, loadCrm, saveCrm, type Account, type ActivityKind, type Contact, type CrmStage, type Location } from "../crmStore";
import "./CRM.css";

const split = (value: string) => value.split(/[,\n]/).map(x => x.trim()).filter(Boolean);
const date = (value: string) => value ? new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(`${value}T12:00:00`)) : "Kein Termin";

export default function CRM() {
  const [accounts, setAccounts] = createSignal<Account[]>(loadCrm());
  const [selected, setSelected] = createSignal<string | null>(null);
  const [query, setQuery] = createSignal("");
  const [newOpen, setNewOpen] = createSignal(false);
  const [filterOwner, setFilterOwner] = createSignal("Alle");
  const [view, setView] = createSignal<"Pipeline" | "Kunden" | "Offene Deals" | "Abgeschlossene Deals" | "Kalender">("Pipeline");
  const [dragging, setDragging] = createSignal<string | null>(null);
  const [dragOverStage, setDragOverStage] = createSignal<CrmStage | null>(null);
  createEffect(() => saveCrm(accounts()));
  const locations = createMemo(() => accounts().flatMap(account => account.locations.map(location => ({ account, location }))));
  const visible = () => locations().filter(({ account, location }) => {
    const q = query().trim().toLocaleLowerCase("de");
    return (!q || `${account.name} ${location.name} ${location.address}`.toLocaleLowerCase("de").includes(q)) && (filterOwner() === "Alle" || account.owner === filterOwner());
  });
  const selectedItem = () => locations().find(item => item.location.id === selected());
  const mutate = (fn: (draft: Account[]) => void) => setAccounts(current => { const next = structuredClone(current); fn(next); return next; });
  const updateLocation = (locationId: string, patch: Partial<Location>) => mutate(items => { for (const account of items) { const loc = account.locations.find(x => x.id === locationId); if (loc) Object.assign(loc, patch); } });
  const move = (locationId: string, stage: CrmStage) => updateLocation(locationId, { stage, status: "Aktiv" });
  const addAccount = (name: string, owner: string) => { const location = emptyLocation(name); const account: Account = { id: id("account"), name, website: "", locationCount: 1, employees: "", software: "", source: "", owner, locations: [location] }; mutate(items => items.unshift(account)); setSelected(location.id); setNewOpen(false); };
  const owners = () => ["Alle", ...Array.from(new Set(accounts().map(x => x.owner).filter(Boolean)))];
  return <section class="crm-view">
    <PageHeader icon="columns" title="CRM" subline="Betriebe und Standorte im Vertrieb verwalten." chips={<Chip value={visible().length} label={visible().length === 1 ? " Standort" : " Standorte"} />} />
    <nav class="page-actionbar crm-toolbar" aria-label="CRM actions">
      <div class="crm-search"><Icon name="search" size={17}/><input value={query()} onInput={e => setQuery(e.currentTarget.value)} placeholder="Betrieb oder Standort suchen" aria-label="Betrieb oder Standort suchen" /></div>
      <select aria-label="Nach verantwortlicher Person filtern" value={filterOwner()} onChange={e => setFilterOwner(e.currentTarget.value)}><For each={owners()}>{owner => <option>{owner}</option>}</For></select>
      <button class="primary" onClick={() => setNewOpen(true)}><Icon name="plus" size={16}/> Betrieb hinzufügen</button>
    </nav>
    <Show when={newOpen()}><NewAccount onClose={() => setNewOpen(false)} onSave={addAccount}/></Show>
    <nav class="crm-view-tabs" aria-label="CRM Ansichten"><For each={["Pipeline", "Kunden", "Offene Deals", "Abgeschlossene Deals", "Kalender"] as const}>{name => <button classList={{ active: view() === name }} onClick={() => setView(name)}>{name}</button>}</For></nav>
    <Show when={view() === "Pipeline"}><div class="crm-board" aria-label="Vertriebspipeline">
      <For each={CRM_STAGES}>{stage => <section class="crm-column" classList={{ "is-drop-target": dragOverStage() === stage }} onDragOver={e => { e.preventDefault(); if (e.dataTransfer) e.dataTransfer.dropEffect = "move"; setDragOverStage(stage); }} onDragLeave={() => setDragOverStage(null)} onDrop={e => { e.preventDefault(); const locationId = e.dataTransfer?.getData("text/plain") || dragging(); if (locationId) move(locationId, stage); setDragging(null); setDragOverStage(null); }}>
        <header><strong>{stage}</strong><span>{visible().filter(x => x.location.stage === stage && x.location.status === "Aktiv").length}</span></header>
        <div class="crm-column-cards"><For each={visible().filter(x => x.location.stage === stage && x.location.status === "Aktiv")}>{item => <div class="crm-card" role="button" tabindex="0" draggable="true" onDragStart={e => { setDragging(item.location.id); if (e.dataTransfer) { e.dataTransfer.effectAllowed = "move"; e.dataTransfer.setData("text/plain", item.location.id); } }} onDragEnd={() => { setDragging(null); setDragOverStage(null); }} onClick={() => setSelected(item.location.id)}>
          <span class="crm-card-account">{item.account.name}</span><strong>{item.location.name}</strong>
          <Show when={item.location.nextStep}><span class="crm-card-next"><Icon name="alert" size={14}/>{item.location.nextStep}</span></Show>
          <footer><span>{item.account.owner || "Nicht zugeteilt"}</span><Show when={item.location.contacts.length}><span>{item.location.contacts.length} Kontakt{item.location.contacts.length === 1 ? "" : "e"}</span></Show></footer>
        </div>}</For></div>
      </section>}</For>
    </div></Show>
    <Show when={view() === "Kunden"}><CustomerDirectory title="Kundenkarteien" items={visible} onOpen={setSelected}/></Show>
    <Show when={view() === "Offene Deals"}><CustomerDirectory title="Offene Deals" items={() => visible().filter(x => x.location.status === "Aktiv" && x.location.stage !== "Gewonnen")} onOpen={setSelected}/></Show>
    <Show when={view() === "Abgeschlossene Deals"}><CustomerDirectory title="Abgeschlossene Deals" items={() => visible().filter(x => x.location.status === "Verloren" || x.location.stage === "Gewonnen")} onOpen={setSelected}/></Show>
    <Show when={view() === "Kalender"}><CrmCalendar items={visible} onOpen={setSelected}/></Show>
    <Show when={selectedItem()}>{item => <Detail locationId={item().location.id} accounts={accounts} onSelect={setSelected} onClose={() => setSelected(null)} onMutate={mutate} onUpdate={updateLocation} onMove={move}/>}</Show>
  </section>;
}

function NewAccount(props: { onClose: () => void; onSave: (name: string, owner: string) => void }) {
  const [name, setName] = createSignal(""); const [owner, setOwner] = createSignal("Jannes");
  return <div class="crm-overlay" role="presentation"><form class="crm-modal" onSubmit={e => { e.preventDefault(); if (name().trim()) props.onSave(name().trim(), owner()); }}><header><h2>Neuen Betrieb anlegen</h2><button type="button" class="icon-button" onClick={props.onClose}><Icon name="close"/></button></header><label>Betriebsname<input autofocus value={name()} onInput={e => setName(e.currentTarget.value)} placeholder="z. B. Optik Musterstadt"/></label><label>Verantwortliche Person<select value={owner()} onChange={e => setOwner(e.currentTarget.value)}><For each={["Jannes", "Bjarne", "Charles", "Pascal"]}>{x => <option>{x}</option>}</For></select></label><p>Der erste Standort wird angelegt und kann anschließend in der Kundenkartei ergänzt werden.</p><footer><button type="button" class="ghost" onClick={props.onClose}>Abbrechen</button><button class="primary">Betrieb anlegen</button></footer></form></div>;
}

function Detail(props: { locationId: string; accounts: () => Account[]; onSelect: (id: string) => void; onClose: () => void; onMutate: (fn: (draft: Account[]) => void) => void; onUpdate: (id: string, patch: Partial<Location>) => void; onMove: (id: string, stage: CrmStage) => void }) {
  const [tab, setTab] = createSignal<"Übersicht" | "Aktivitäten" | "Dokumente">("Übersicht");
  const location = () => props.accounts().flatMap(x => x.locations).find(x => x.id === props.locationId)!;
  const account = () => props.accounts().find(x => x.locations.some(location => location.id === props.locationId))!;
  const patchAccount = (patch: Partial<Account>) => props.onMutate(items => { const found = items.find(x => x.id === account().id); if (found) Object.assign(found, patch); });
  const addContact = () => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); loc?.contacts.push({ id: id("contact"), name: "", role: "", emails: [], phones: [], preferred: "" }); });
  const addNote = (body: string) => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); if (loc && body.trim()) loc.notes.unshift({ id: id("note"), body: body.trim(), author: "Team paloptic", createdAt: new Date().toISOString() }); });
  const addActivity = (kind: ActivityKind, title: string, dueDate: string) => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); if (loc && title.trim()) loc.activities.unshift({ id: id("activity"), kind, title, dueDate, outcome: "", done: false }); });
  const addLocation = () => props.onMutate(items => { const found = items.find(x => x.id === account().id); if (found) { found.locations.push(emptyLocation(`${found.name} · Neuer Standort`)); found.locationCount = found.locations.length; } });
  return <aside class="crm-detail" aria-label={`Kundenkartei ${location().name}`}>
    <header class="crm-detail-head"><div><button class="crm-back" onClick={props.onClose}><Icon name="chevron-left" size={17}/> Pipeline</button><p>{account().name}</p><h1>{location().name}</h1></div><button class="icon-button" onClick={props.onClose} aria-label="Kundenkartei schließen"><Icon name="close"/></button></header>
    <div class="crm-stage-row"><select value={location().stage} onChange={e => props.onMove(location().id, e.currentTarget.value as CrmStage)}><For each={CRM_STAGES}>{stage => <option>{stage}</option>}</For></select><button class="ghost danger" onClick={() => props.onUpdate(location().id, { status: "Verloren" })}>Als verloren markieren</button></div>
    <nav class="crm-tabs"><For each={["Übersicht", "Aktivitäten", "Dokumente"] as const}>{name => <button classList={{ active: tab() === name }} onClick={() => setTab(name)}>{name}</button>}</For></nav>
    <Show when={tab() === "Übersicht"}><div class="crm-detail-body"><section class="crm-section"><h2>Betrieb</h2><div class="crm-fields two"><Field label="Betriebsname" value={account().name} onChange={value => patchAccount({ name: value })}/><Field label="Website" value={account().website} onChange={value => patchAccount({ website: value })}/><Field label="Anzahl Standorte" value={String(account().locationCount)} onChange={value => patchAccount({ locationCount: Number(value) || 0 })}/><Field label="Anzahl Mitarbeitende" value={account().employees} onChange={value => patchAccount({ employees: value })}/><Field label="Branchensoftware" value={account().software} onChange={value => patchAccount({ software: value })}/><Field label="Quelle" value={account().source} onChange={value => patchAccount({ source: value })}/><Field label="Verantwortliche Person" value={account().owner} onChange={value => patchAccount({ owner: value })}/></div></section>
      <section class="crm-section"><div class="crm-section-title"><h2>Standorte</h2><button class="ghost small" onClick={addLocation}><Icon name="plus" size={14}/> Standort hinzufügen</button></div><div class="crm-location-list"><For each={account().locations}>{loc => <button classList={{ active: loc.id === location().id }} onClick={() => props.onSelect(loc.id)}>{loc.name}<small>{loc.stage}</small></button>}</For></div><h3>Kontaktdaten dieses Standorts</h3><label>Adresse<textarea value={location().address} onInput={e => props.onUpdate(location().id, { address: e.currentTarget.value })} placeholder="Straße, Hausnummer&#10;PLZ Ort"/></label><Field label="E-Mail-Adressen" value={location().emails.join(", ")} onChange={value => props.onUpdate(location().id, { emails: split(value) })}/><Field label="Telefonnummern" value={location().phones.join(", ")} onChange={value => props.onUpdate(location().id, { phones: split(value) })}/></section>
      <section class="crm-section"><div class="crm-section-title"><h2>Ansprechpartner</h2><button class="ghost small" onClick={addContact}><Icon name="plus" size={14}/> Kontakt</button></div><For each={location().contacts}>{contact => <ContactForm contact={contact} onPatch={patch => props.onMutate(items => { const found = items.flatMap(x => x.locations).find(x => x.id === location().id)?.contacts.find(x => x.id === contact.id); if (found) Object.assign(found, patch); })}/>}</For><Show when={!location().contacts.length}><p class="crm-empty">Noch keine Ansprechpartner hinterlegt.</p></Show></section>
      <section class="crm-section"><h2>Nächster Schritt</h2><Field label="Aufgabe / nächster Kontakt" value={location().nextStep} onChange={value => props.onUpdate(location().id, { nextStep: value })}/><label>Fällig am<input type="date" value={location().nextStepDate} onInput={e => props.onUpdate(location().id, { nextStepDate: e.currentTarget.value })}/></label></section>
      <Notes notes={location().notes} onAdd={addNote}/></div></Show>
    <Show when={tab() === "Aktivitäten"}><Activities activities={location().activities} onAdd={addActivity} onToggle={activityId => props.onMutate(items => { const a = items.flatMap(x => x.locations).find(x => x.id === location().id)?.activities.find(x => x.id === activityId); if (a) a.done = !a.done; })}/></Show>
    <Show when={tab() === "Dokumente"}><Files location={location} onAdd={file => props.onMutate(items => { const loc = items.flatMap(x => x.locations).find(x => x.id === location().id); loc?.files.unshift(file); })}/></Show>
  </aside>;
}
const Field = (props: { label: string; value: string; onChange: (value: string) => void }) => <label>{props.label}<input value={props.value} onInput={e => props.onChange(e.currentTarget.value)}/></label>;
function CustomerDirectory(props: { title: string; items: () => { account: Account; location: Location }[]; onOpen: (id: string) => void }) { return <section class="crm-directory"><header><div><h2>{props.title}</h2><p>Standort auswählen, um die vollständige Kundenkartei zu öffnen.</p></div><span>{props.items().length}</span></header><div class="crm-directory-table"><div class="crm-directory-head"><span>Standort</span><span>Betrieb</span><span>Pipeline</span><span>Nächster Schritt</span><span>Verantwortlich</span></div><For each={props.items()}>{item => <button onClick={() => props.onOpen(item.location.id)}><strong>{item.location.name}</strong><span>{item.account.name}</span><span class="crm-stage-chip">{item.location.status === "Verloren" ? "Verloren" : item.location.stage}</span><span>{item.location.nextStep || "—"}</span><span>{item.account.owner || "—"}</span></button>}</For></div><Show when={!props.items().length}><p class="crm-empty">Keine Einträge in dieser Ansicht.</p></Show></section> }
function CrmCalendar(props: { items: () => { account: Account; location: Location }[]; onOpen: (id: string) => void }) { const activities = () => props.items().flatMap(item => item.location.activities.filter(a => !a.done).map(activity => ({ ...item, activity }))).sort((a,b) => a.activity.dueDate.localeCompare(b.activity.dueDate)); return <section class="crm-directory crm-calendar"><header><div><h2>CRM-Kalender</h2><p>Offene Aktivitäten und nächste Schritte nach Datum.</p></div><span>{activities().length}</span></header><For each={activities()}>{entry => <button class="crm-calendar-row" onClick={() => props.onOpen(entry.location.id)}><time>{date(entry.activity.dueDate)}</time><span><strong>{entry.activity.kind} · {entry.activity.title}</strong><small>{entry.location.name} · {entry.account.name}</small></span><Icon name="chevron-right" size={17}/></button>}</For><Show when={!activities().length}><p class="crm-empty">Noch keine offenen Aktivitäten geplant.</p></Show></section> }
function ContactForm(props: { contact: Contact; onPatch: (patch: Partial<Contact>) => void }) { return <div class="crm-contact"><div class="crm-fields two"><Field label="Name" value={props.contact.name} onChange={name => props.onPatch({ name })}/><Field label="Rolle" value={props.contact.role} onChange={role => props.onPatch({ role })}/><Field label="E-Mail-Adressen" value={props.contact.emails.join(", ")} onChange={value => props.onPatch({ emails: split(value) })}/><Field label="Telefonnummern" value={props.contact.phones.join(", ")} onChange={value => props.onPatch({ phones: split(value) })}/></div><Field label="Bevorzugter Kontaktweg" value={props.contact.preferred} onChange={preferred => props.onPatch({ preferred })}/></div>; }
function Notes(props: { notes: Location["notes"]; onAdd: (body: string) => void }) { const [body, setBody] = createSignal(""); return <section class="crm-section"><h2>Notizen</h2><form class="crm-add-note" onSubmit={e => { e.preventDefault(); props.onAdd(body()); setBody(""); }}><textarea value={body()} onInput={e => setBody(e.currentTarget.value)} placeholder="Gesprächsnotiz festhalten…"/><button class="primary">Notiz speichern</button></form><For each={props.notes}>{note => <article class="crm-note"><p>{note.body}</p><small>{note.author} · {new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(note.createdAt))}</small></article>}</For></section>; }
function Activities(props: { activities: Location["activities"]; onAdd: (kind: ActivityKind, title: string, due: string) => void; onToggle: (id: string) => void }) { const [kind, setKind] = createSignal<ActivityKind>("Anruf"); const [title, setTitle] = createSignal(""); const [due, setDue] = createSignal(""); return <div class="crm-detail-body"><section class="crm-section"><h2>Aktivität planen</h2><form class="crm-activity-form" onSubmit={e => { e.preventDefault(); props.onAdd(kind(), title(), due()); setTitle(""); setDue(""); }}><select value={kind()} onChange={e => setKind(e.currentTarget.value as ActivityKind)}><For each={["Anruf", "E-Mail", "Besuch", "Video-Call", "Aufgabe"] as ActivityKind[]}>{x => <option>{x}</option>}</For></select><input value={title()} onInput={e => setTitle(e.currentTarget.value)} placeholder="Was ist zu tun?"/><input type="date" value={due()} onInput={e => setDue(e.currentTarget.value)}/><button class="primary">Hinzufügen</button></form></section><section class="crm-section"><h2>Verlauf</h2><For each={props.activities}>{activity => <label class="crm-activity"><input type="checkbox" checked={activity.done} onChange={() => props.onToggle(activity.id)}/><span><strong>{activity.kind} · {activity.title}</strong><small>{date(activity.dueDate)}</small></span></label>}</For><Show when={!props.activities.length}><p class="crm-empty">Noch keine Aktivitäten geplant.</p></Show></section></div>; }
function Files(props: { location: () => Location; onAdd: (file: Location["files"][number]) => void }) { const upload = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => props.onAdd({ id: id("file"), name: file.name, type: file.type, data: String(reader.result), createdAt: new Date().toISOString() }); reader.readAsDataURL(file); }; return <div class="crm-detail-body"><section class="crm-section"><h2>Dokumente</h2><label class="crm-upload"><Icon name="upload" size={20}/><span>Datei hinzufügen</span><input type="file" onChange={e => upload(e.currentTarget.files?.[0])}/></label><p class="crm-muted">Angebote, Verträge und weitere Unterlagen werden direkt an diesem Standort hinterlegt.</p><For each={props.location().files}>{file => <a class="crm-file" href={file.data} download={file.name}><Icon name="doc" size={18}/><span><strong>{file.name}</strong><small>{date(file.createdAt.slice(0, 10))}</small></span></a>}</For><Show when={!props.location().files.length}><p class="crm-empty">Noch keine Dokumente hinterlegt.</p></Show></section></div>; }
