import { createResource, createSignal, For, Show } from "solid-js";
import { platformApi, type Location } from "../api/platform";
import { WorkspaceHeader } from "../components/WorkspaceHeader";
import { humanError } from "../session";
const blank = (): Location => ({ id:"", name:"", location_type:"Office", parent_id:null, timezone:Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", work_schedule_json:'{"workdays":[1,2,3,4,5]}', channel_id:null, archived:false, equipment:[] });
export default function Locations() {
  const [locations,{refetch}] = createResource(() => platformApi.locations());
  const [draft,setDraft] = createSignal<Location>(blank()); const [error,setError] = createSignal("");
  const save = async (event: SubmitEvent) => { event.preventDefault(); try { await platformApi.saveLocation({...draft(), equipment:draft().equipment.filter(Boolean)}); setDraft(blank()); await refetch(); } catch (e) { setError(humanError(e)); } };
  return <section class="settings-view"><WorkspaceHeader icon="org" title="Locations">Office timezones, work schedules, equipment, and their linked chat channels.</WorkspaceHeader><Show when={error()}><p class="meeting-error">{error()}</p></Show><div class="settings-grid"><form class="settings-card" onSubmit={save}><h2>{draft().id ? "Edit location" : "New location"}</h2><label>Name<input required value={draft().name} onInput={e=>setDraft({...draft(),name:e.currentTarget.value})}/></label><label>Type<input value={draft().location_type} onInput={e=>setDraft({...draft(),location_type:e.currentTarget.value})}/></label><label>Timezone<input required value={draft().timezone} onInput={e=>setDraft({...draft(),timezone:e.currentTarget.value})}/></label><label>Work schedule JSON<textarea value={draft().work_schedule_json} onInput={e=>setDraft({...draft(),work_schedule_json:e.currentTarget.value})}/></label><label>Equipment (comma-separated)<input value={draft().equipment.join(", ")} onInput={e=>setDraft({...draft(),equipment:e.currentTarget.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><button class="primary">Save location</button></form><div class="settings-card"><h2>Locations</h2><For each={locations()}>{location=><button class="meeting-row" type="button" onClick={()=>setDraft({...location,equipment:[...location.equipment]})}><strong>{location.name}</strong><span>{location.location_type} · {location.timezone}</span><span>{location.equipment.join(", ") || "No equipment"}</span><Show when={location.channel_id}><small>Chat linked</small></Show></button>}</For></div></div></section>;
}
