import { createEffect, createMemo, createSignal, Show } from "solid-js";
import { platformApi } from "../api/platform";
import { currentUser, humanError, profileId, projects, reloadProjects, setProjectId } from "../session";
import { linkProps, route } from "../router";
import "./ProjectSettings.css";

export default function ProjectSettings() {
  const id = () => route().projectId ?? "";
  const project = createMemo(() => (projects() ?? []).find(item => item.id === id()));
  const [name, setName] = createSignal(""); const [description, setDescription] = createSignal(""); const [deadline, setDeadline] = createSignal("");
  const [error, setError] = createSignal(""); const [notice, setNotice] = createSignal(""); const [saving, setSaving] = createSignal(false); const [confirm, setConfirm] = createSignal(false);
  createEffect(() => { const value = project(); setName(value?.name ?? ""); setDescription(value?.description ?? ""); setDeadline(value?.deadline ?? ""); });
  const editable = () => !!project() && (currentUser()?.role === "admin" || project()!.created_by === profileId());
  const save = async () => { const value = project(); if (!value || !editable()) return; if (!name().trim()) return setError("A project needs a name."); setSaving(true); setError(""); try { await platformApi.updateProject({ ...value, name: name().trim(), description: description().trim() || null, deadline: deadline() || null }); await reloadProjects(); setNotice("Project settings saved."); } catch (reason) { setError(humanError(reason)); } finally { setSaving(false); } };
  const archive = async () => { const value = project(); if (!value || !editable()) return; setSaving(true); try { await platformApi.updateProject({ ...value, archived: true }); const all = await reloadProjects(); setProjectId(all.find(item => !item.archived)?.id ?? ""); } catch (reason) { setError(humanError(reason)); } finally { setSaving(false); } };
  return <section class="ps-view"><header class="ps-head"><div class="ps-identity"><div class="ps-mark">{project()?.key.slice(0, 2) ?? "··"}</div><div><h1>Project settings</h1><p>{project()?.name ?? "Project"}</p></div></div></header><Show when={!project()}><p class="ps-empty">This project is unavailable.</p></Show><Show when={project()}><Show when={error()}><p class="ps-error" role="alert">{error()}</p></Show><Show when={notice()}><p class="ps-notice">{notice()}</p></Show><Show when={!editable()}><p class="ps-notice">Only the project owner or an administrator can change these settings.</p></Show><div class="ps-grid"><section class="ps-panel ps-panel-wide"><div class="ps-panel-head"><h2>Overview</h2></div><label class="ps-field"><span>Name</span><input value={name()} disabled={!editable()} onInput={event => setName(event.currentTarget.value)}/></label><label class="ps-field"><span>Description</span><textarea value={description()} disabled={!editable()} onInput={event => setDescription(event.currentTarget.value)}/></label><label class="ps-field"><span>Deadline <em>optional</em></span><input type="date" value={deadline()} disabled={!editable()} onInput={event => setDeadline(event.currentTarget.value)}/></label><p class="ps-hint">Key <strong>{project()!.key}</strong> is fixed after creation.</p><div class="ps-actions"><button class="primary" disabled={!editable() || saving()} onClick={save}>{saving() ? "Saving…" : "Save changes"}</button></div></section></div><Show when={editable()}><section class="ps-danger"><div class="ps-danger-row"><div><strong>Archive this project</strong><p>It remains recoverable; nothing is deleted.</p></div><Show when={confirm()} fallback={<button class="danger-outline" onClick={() => setConfirm(true)}>Archive project</button>}><div class="ps-confirm"><button class="ghost" onClick={() => setConfirm(false)}>Cancel</button><a class="ghost" {...linkProps({ view: "Projects" })}>Keep project</a><button class="danger" disabled={saving()} onClick={archive}>Archive</button></div></Show></div></section></Show></Show></section>;
}
