import { createResource, createSignal, For, Show, onMount } from "solid-js";
import { personalApi, type Todo as TodoItem } from "../api/personal";
import "./Todo.css";
import { ProfilePicker } from "../components/Pickers";
import { WorkspaceHeader } from "../components/WorkspaceHeader";
import { profileId, profiles, reloadProfiles, projects, reloadProjects } from "../session";
import { humanError } from "../session";

const blank = () => ({ content:"", due_date:"", project_id:"", source_entity_type:"", source_entity_id:"", assignee_ids:[] as string[] });
export default function Todo() {
  onMount(()=>{ void reloadProfiles(); void reloadProjects(); });
  const [form,setForm]=createSignal(blank()); const [error,setError]=createSignal("");
  const [todos,{refetch}]=createResource(profileId,id=>id?personalApi.todos(id,true):Promise.resolve([]));
  const [projectMembers]=createResource(()=>form().project_id,id=>id?personalApi.projectMemberIds(id):Promise.resolve([]));
  const active=()=>profiles()?.filter(p=>!p.archived)??[];
  const nameOf=(id:string)=>{ const p=active().find(x=>x.id===id); return p?(p.display_name||p.username):id; };
  const projectName=(id:string)=>projects()?.find(project=>project.id===id)?.name??id;
  const personalTodos=()=>todos()?.filter(todo=>!todo.project_id)??[];
  const groupedTodos=()=>todos()?.filter(todo=>todo.project_id)??[];
  const addAssignee=(id:string)=>{ if(!id || !form().project_id) return; const f=form(); if(f.assignee_ids.includes(id)) return; setForm({...f,assignee_ids:[...f.assignee_ids,id]}); };
  const removeAssignee=(id:string)=>{ const f=form(); setForm({...f,assignee_ids:f.assignee_ids.filter(x=>x!==id)}); };
  const selectProject=(id:string)=>setForm({...form(),project_id:id,assignee_ids:id?form().assignee_ids:[]});
  const save=async(e:SubmitEvent)=>{ e.preventDefault(); try { if(!profileId().trim()||!form().content.trim()) throw new Error("Pick a profile and enter task content."); const f=form(); if(Boolean(f.source_entity_type)!==Boolean(f.source_entity_id)) throw new Error("Source type and source ID must be supplied together."); await personalApi.createTodo({profile_id:profileId().trim(),content:f.content.trim(),due_date:f.due_date||null,project_id:f.project_id||null,done:false,source_entity_type:f.source_entity_type||null,source_entity_id:f.source_entity_id||null,assignee_ids:f.assignee_ids}); setForm(blank()); refetch(); } catch(reason) { setError(humanError(reason)); } };
  const complete=async(todo:TodoItem, done:boolean)=>{ try { await personalApi.setTodoCompletion(todo.id,done); refetch(); } catch(reason) { setError(humanError(reason)); } };
  const todoRow=(todo:TodoItem)=><article classList={{"todo-row":true,done:todo.done}}><input aria-label={`Mark ${todo.content} done`} type="checkbox" checked={todo.done} onChange={e=>complete(todo,e.currentTarget.checked)}/><div><strong>{todo.content}</strong><Show when={todo.project_id}>{id=><small>Project · {projectName(id())}</small>}</Show><Show when={todo.due_date}><time>Due {todo.due_date}</time></Show><Show when={todo.assignee_ids.length}><ul class="assignee-chips readonly"><For each={todo.assignee_ids}>{id=><li class="assignee-chip">{nameOf(id)}</li>}</For></ul></Show><Show when={todo.source_entity_type}><small>{todo.source_entity_type}: {todo.source_entity_id}</small></Show></div><button class="ghost" title="Delete task" onClick={async()=>{try{await personalApi.deleteTodo(todo.id);refetch()}catch(reason){setError(humanError(reason))}}}>×</button></article>;
  return <section class="personal-view"><WorkspaceHeader icon="✓" title="My tasks" actions={<ProfilePicker locked/>}>Personal tasks and project work, scoped to the people attached to each project.</WorkspaceHeader><Show when={error()}><p class="personal-error">{error()}</p></Show><div class="todo-layout"><form class="personal-card todo-form" onSubmit={save}><h2>New task</h2><input autofocus placeholder="What needs doing?" value={form().content} onInput={e=>setForm({...form(),content:e.currentTarget.value})}/><label>Due date<input type="date" value={form().due_date} onInput={e=>setForm({...form(),due_date:e.currentTarget.value})}/></label><label>Project<select value={form().project_id} onChange={e=>selectProject(e.currentTarget.value)}><option value="">Personal</option><For each={(projects()??[]).filter(project=>!project.archived)}>{project=><option value={project.id}>{project.name}</option>}</For></select></label><label>Assignees<select value="" disabled={!form().project_id} title={!form().project_id?"Select a project before assigning members":undefined} onChange={e=>{addAssignee(e.currentTarget.value);e.currentTarget.value="";}}><option value="">Add project member…</option><For each={active().filter(p=>(projectMembers()??[]).includes(p.id)&&!form().assignee_ids.includes(p.id))}>{p=><option value={p.id}>{p.display_name||p.username}</option>}</For></select></label><Show when={!form().project_id}><p class="hint">Select a project to assign its members.</p></Show><Show when={form().project_id&&!projectMembers.loading&&!projectMembers()?.length}><p class="hint">This project has no members available for assignment.</p></Show><Show when={form().assignee_ids.length}><ul class="assignee-chips"><For each={form().assignee_ids}>{id=><li class="assignee-chip">{nameOf(id)}<button type="button" aria-label={`Remove ${nameOf(id)}`} onClick={()=>removeAssignee(id)}>×</button></li>}</For></ul></Show><details><summary>Source bookmark</summary><input placeholder="Entity type (issue, document…)" value={form().source_entity_type} onInput={e=>setForm({...form(),source_entity_type:e.currentTarget.value})}/><input placeholder="Entity ID" value={form().source_entity_id} onInput={e=>setForm({...form(),source_entity_id:e.currentTarget.value})}/></details><button class="primary">Add task</button></form><div class="todo-list"><Show when={!profileId()}><p class="personal-empty">No profile selected — add one in Members.</p></Show><section class="todo-group"><h2>Personal</h2><Show when={!personalTodos().length}><p class="personal-empty">No personal tasks.</p></Show><For each={personalTodos()}>{todoRow}</For></section><Show when={groupedTodos().length}><section class="todo-group"><h2>Projects</h2><For each={groupedTodos()}>{todoRow}</For></section></Show></div></div></section>;
}
