import { createEffect, createResource, createSignal, For, Show } from "solid-js";
import { personalApi, type FullTextResult, type GotoResult } from "../api/personal";
import { entityView, hrefFor, isViewAvailable } from "../router";
import "./Goto.css";
type Props = { open:boolean; fullText?:boolean; onClose:()=>void; onNavigate:(entityType:string,entityId:string)=>void };
type Mode="goto"|"fulltext";
const labels:Record<string,string>={profile:"People",project:"Projects",issue:"Tickets",channel:"Channels",document:"Documents",review:"Code reviews",meeting:"Meetings",blog:"Blogs"};
export default function Goto(props:Props) {
 const [query,setQuery]=createSignal(""); const [mode,setMode]=createSignal<Mode>(props.fullText?"fulltext":"goto"); let input!:HTMLInputElement;
 createEffect(()=>{if(props.open){setMode(props.fullText?"fulltext":"goto");requestAnimationFrame(()=>input?.focus())}});
 const [goto]=createResource(query,term=>term.trim()?personalApi.gotoSearch(term):Promise.resolve([] as GotoResult[]));
 const [fulltext]=createResource(()=>[query(),mode()] as const,([term,next])=>next==="fulltext"&&term.trim()?personalApi.fullTextSearch(term):Promise.resolve([] as FullTextResult[]));
 const reachableGoto=()=> (goto()??[]).filter(result=>{const view=entityView(result.entity_type);return !view||isViewAvailable(view)});
 const reachableFts=()=> (fulltext()??[]).filter(result=>{const view=entityView(result.entity_type);return !!view&&isViewAvailable(view)});
 const groups=()=>Object.entries(reachableGoto().reduce<Record<string,GotoResult[]>>((all,result)=>{(all[result.entity_type]??=[]).push(result);return all},{}));
 const choose=(result:{entity_type:string;id:string})=>{props.onNavigate(result.entity_type,result.id);props.onClose();setQuery("")};
 const loading=()=>mode()==="goto"?goto.loading:fulltext.loading; const results=()=>mode()==="goto"?reachableGoto():reachableFts();
 return <Show when={props.open}><div class="goto-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)props.onClose()}}><section class="goto-modal" role="dialog" aria-label="Search workspace"><div class="goto-input"><span>⌕</span><input ref={input} value={query()} onInput={event=>setQuery(event.currentTarget.value)} onKeyDown={event=>{if(event.key==="Escape")props.onClose();if(event.key==="Enter"&&results()[0])choose(results()[0])}} placeholder={mode()==="goto"?"Go to people, projects, tickets, channels, documents…":"Search tickets, documents, chats, and blogs…"}/><kbd>Esc</kbd></div><div class="goto-tabs"><button classList={{active:mode()==="goto"}} onClick={()=>setMode("goto")}>Go to <kbd>⌘K</kbd></button><button classList={{active:mode()==="fulltext"}} onClick={()=>setMode("fulltext")}>Full text <kbd>⌘⇧F</kbd></button></div><Show when={loading()}><p class="goto-muted">Searching…</p></Show><Show when={query()&&!loading()&&!results().length}><p class="goto-muted">No matching results.</p></Show><div class="goto-results"><Show when={mode()==="goto"} fallback={<For each={reachableFts()}>{result=><a href={hrefFor({view:entityView(result.entity_type)!,entityType:result.entity_type,entityId:result.id})} onClick={event=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();choose(result)}}><span class="goto-icon">{result.entity_type.slice(0,1).toUpperCase()}</span><span><strong>{result.title||labels[result.entity_type]||result.entity_type}</strong><small>{result.breadcrumb}</small><em>{result.snippet.replace(/<mark>|<\/mark>/g, "")}</em></span></a>}</For>}><For each={groups()}>{([kind,items])=><section><h2>{labels[kind]??kind}</h2><For each={items}>{result=><a href={hrefFor({view:entityView(result.entity_type)??"Dashboard",entityType:result.entity_type,entityId:result.id})} onClick={event=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();choose(result)}}><span class="goto-icon">{kind.slice(0,1).toUpperCase()}</span><span><strong>{result.title||result.id}</strong><small>{result.details}</small></span></a>}</For></section>}</For></Show></div><footer><span>↵ Open first result</span><span>{mode()==="goto"?"Quick navigation":"Ranked content results"}</span></footer></section></div></Show>;
}
